image:
  file: .gitpod.Dockerfile  # Define custom Dockerfile for environment setup

tasks:
  - init: |
      sudo apt-get update && sudo apt-get install -y git python3-pip
      git clone https://github.com/pandas-dev/pandas
      git clone https://github.com/scikit-learn/scikit-learn
      pip install -r pandas/requirements-dev.txt      # Install dev dependencies for pandas
      pip install -r scikit-learn/requirements.txt    # Install dependencies for scikit-learn
    command: |
      git status   # Example command for workspace testing

vscode:
  extensions:
    - Supermaven.supermaven  # Install the SuperMaven extension automatically

ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    master: true  # Enable prebuilds for faster environment setup


